import { Filter, Search, SlidersHorizontal } from 'lucide-react'
import EmptyState from './EmptyState'

function ResourceTable({ resources = [], metrics = [], loading = false, fullPage = false }) {
  const columns = ['Resource ID', 'Type', 'Status', 'Region', 'Environment', 'Owner', 'Estimated Cost', 'Utilization', 'Actions']
  const metricsById = Object.fromEntries(metrics.map((metric) => [metric.instance_id, metric]))
  return <section className={`panel resource-panel ${fullPage ? 'resource-page' : ''}`}><div className="panel-heading"><div><span className="eyebrow">AWS inventory</span><h2>Resources</h2><p>EC2 resources discovered by the latest read-only scan</p></div><button className="secondary-button" title="Column configuration is not persisted"><SlidersHorizontal size={15} /> Configure columns</button></div><div className="table-toolbar"><label className="search-box"><Search size={16} /><input placeholder="Search resources" aria-label="Search resources" /></label><button className="filter-button"><Filter size={15} /> Filters <span>0</span></button><button className="filter-button">Sort by <b>Last scanned</b></button></div><div className="table-wrap"><table><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={columns.length}><EmptyState loading title="Loading resources" /></td></tr> : resources.length ? resources.map((resource) => { const tags = resource.tags || {}; const metric = metricsById[resource.instance_id]; return <tr key={resource.instance_id}><td><strong className="resource-id">{resource.instance_id || 'Unavailable'}</strong></td><td>{resource.instance_type || 'Unavailable'}</td><td><span className={`state-label ${resource.state || 'unknown'}`}>{resource.state || 'Unavailable'}</span></td><td>{resource.availability_zone || 'Unavailable'}</td><td>{tags.Environment || tags.environment || 'Unassigned'}</td><td>{tags.Owner || tags.owner || 'Unassigned'}</td><td>Unavailable</td><td>{metric?.cpu_average != null ? `${metric.cpu_average}%` : 'Unavailable'}</td><td><button className="text-button">Details</button></td></tr> }) : <tr><td colSpan={columns.length}><EmptyState title="No AWS resources discovered" description="Connect AWS read access and run a scan to populate this table." /></td></tr>}</tbody></table></div><div className="pagination"><span>Showing {resources.length} resources</span><span>{metrics.length ? 'Utilization data available' : 'Utilization unavailable'}</span></div></section>
}

export default ResourceTable
